### ISSUE TITLE
After Update the extension did no more work in on-premise installation

### ISSUE THREAD

**Issue by weird-dreams** [ostreifel/Board-Group#12]
The board group in my work item only shows:
![shot_304](https://user-images.githubusercontent.com/11518242/32669990-a18a936c-c642-11e7-8bf8-3a92e3184c4d.png)
And the action is no more present in the context menu of a work item in the board.

Please tell me what to do or if you may have a fix for us.

By the way - we used your extension very often !

Our TFS Version (on premise)
Microsoft Visual Studio Team Foundation Server
Version 15.105.25910.0

**Comment by ostreifel** [comment]
Are you getting an exception the browser console (f12)?

**Comment by weird-dreams** [comment]
Sorry - missed to put it in:
TypeError: Object doesn't support property or method 'getBacklogConfigurations'
   at Anonymous function (http://wdtfs2:8080/tfs/_apis/public/gallery/publisher/ottostreifel/extension/board-group/2.4.62/assetbyname/scripts/boardGroup.js:1:13220)
   at e.prototype.getValue (http://wdtfs2:8080/tfs/_apis/public/gallery/publisher/ottostreifel/extension/board-group/2.4.62/assetbyname/scripts/boardGroup.js:1:11665)
   at a (http://wdtfs2:8080/tfs/_apis/public/gallery/publisher/ottostreifel/extension/board-group/2.4.62/assetbyname/scripts/boardGroup.js:1:13448)
   at Anonymous function (http://wdtfs2:8080/tfs/_apis/public/gallery/publisher/ottostreifel/extension/board-group/2.4.62/assetbyname/scripts/boardGroup.js:1:4259)
   at Anonymous function (http://wdtfs2:8080/tfs/_apis/public/gallery/publisher/ottostreifel/extension/board-group/2.4.62/assetbyname/scripts/boardGroup.js:1:4124)
   at c (http://wdtfs2:8080/tfs/_public/_Bundling/Content?bundle=vss-bundle-ext-core-vQxYq4ATMXC8TGrjx_LXvb3hM1QKbz3O5KT4mtlpMF_Q=:27:80

**Comment by ostreifel** [comment]
Updated to 2.6.64. Please verify this fixes.

**Comment by weird-dreams** [comment]
Thank you! It is now working again on-premise.
It looks great now (with icons in the context menu)!
I just recognized that you display the Definition of Done as tooltip - very nice!
I wrote a five star review...

**Comment by weird-dreams** [comment]
Could you please rename the context menu from "row" to "swimlane" - that's what it is on a board.

**Comment by ostreifel** [comment]
Updated to use swimlanes on form and in context menus.

Thanks for the review!

**Comment by MagnusTim** [comment]
Hi, I have the same problem with TFS 2017.3 and 2.5.48

Where can I download  2.6.64.? I Can not se it on Marketplace?

Error(s):
TF400813: Resource not available for anonymous access. Client authentication required.

Session Id: 884ea78c-d392-48d8-947f-4639ae874f03

Project 'c95c4180-d9db-4a6c-8c43-3efe497c215b' does not exist.
VSS.WorkItemTracking.ProjectDoesNotExistException: Project 'c95c4180-d9db-4a6c-8c43-3efe497c215b' does not exist.
    at oi (http://tfs:8080/tfs/_public/_Bundling/Content?bundle=vss-bundle-area-vux06pIPzOUTPNwZ5jvGlXRoMtDrtROcijyqGUEX82Qw=:35:1831)
    at hr (http://tfs:8080/tfs/_public/_Bundling/Content?bundle=vss-bundle-area-vux06pIPzOUTPNwZ5jvGlXRoMtDrtROcijyqGUEX82Qw=:35:2015)
    at t.getProject (http://tfs:8080/tfs/_public/_Bundling/Content?bundle=vss-bundle-area-vux06pIPzOUTPNwZ5jvGlXRoMtDrtROcijyqGUEX82Qw=:35:15721)
    at f (http://tfs:8080/tfs/_public/_Bundling/Content?bundle=vss-bundle-area-vux06pIPzOUTPNwZ5jvGlXRoMtDrtROcijyqGUEX82Qw=:35:16035)
    at http://tfs:8080/tfs/_public/_Bundling/Content?bundle=vss-bundle-area-vux06pIPzOUTPNwZ5jvGlXRoMtDrtROcijyqGUEX82Qw=:35:16493
    at c (http://tfs:8080/tfs/_public/_Bundling/Content?bundle=vss-bundle-common-vHMu9W_H19ZO_Am-VJjuKtgKblidS4MH5FJpFq-VZ2JY=:28:8039)
    at http://tfs:8080/tfs/_public/_Bundling/Content?bundle=vss-bundle-common-vHMu9W_H19ZO_Am-VJjuKtgKblidS4MH5FJpFq-VZ2JY=:28:8305
    at t.u.promiseDispatch (http://tfs:8080/tfs/_public/_Bundling/Content?bundle=vss-bundle-common-vHMu9W_H19ZO_Am-VJjuKtgKblidS4MH5FJpFq-VZ2JY=:28:2872)
    at http://tfs:8080/tfs/_public/_Bundling/Content?bundle=vss-bundle-common-vHMu9W_H19ZO_Am-VJjuKtgKblidS4MH5FJpFq-VZ2JY=:28:1653
    at MessagePort.t (http://tfs:8080/tfs/_public/_Bundling/Content?bundle=vss-bundle-common-vHMu9W_H19ZO_Am-VJjuKtgKblidS4MH5FJpFq-VZ2JY=:28:5777)

Session Id: 884ea78c-d392-48d8-947f-4639ae874f03

TF400893: Unable to contact the server. This is most likely caused by a network error. Please check your connection and try again.

TFS.Core.Ajax.NetworkException: TF400893: Unable to contact the server. This is most likely caused by a network error. Please check your connection and try again.
    at ct (http://tfs:8080/tfs/_public/_Bundling/Content?bundle=vss-bundle-common-vHMu9W_H19ZO_Am-VJjuKtgKblidS4MH5FJpFq-VZ2JY=:139:6285)
    at http://tfs:8080/tfs/_public/_Bundling/Content?bundle=vss-bundle-common-vHMu9W_H19ZO_Am-VJjuKtgKblidS4MH5FJpFq-VZ2JY=:139:1574
    at n._func (http://tfs:8080/tfs/_public/_Bundling/Content?bundle=vss-bundle-common-vHMu9W_H19ZO_Am-VJjuKtgKblidS4MH5FJpFq-VZ2JY=:51:217)
    at n._invoke (http://tfs:8080/tfs/_public/_Bundling/Content?bundle=vss-bundle-common-vHMu9W_H19ZO_Am-VJjuKtgKblidS4MH5FJpFq-VZ2JY=:51:4559)
    at http://tfs:8080/tfs/_public/_Bundling/Content?bundle=vss-bundle-common-vHMu9W_H19ZO_Am-VJjuKtgKblidS4MH5FJpFq-VZ2JY=:51:3360

**Comment by ostreifel** [comment]
Can you send a [fiddler trace](http://docs.telerik.com/platform/knowledge-base/how-to/how-to-capture-fiddler-trace) to ottost@microsoft.com?

2.6 is a typo it should be 2.4.64.

**Comment by ostreifel** [comment]
Updated. Let me know if there are any more regressions.

**Comment by MagnusTim** [comment]
It worked, thanks for great support
